name: saferagpp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cpuonly         # ensures CPU builds of pytorch stack
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - matplotlib=3.8.4
  - faiss-cpu=1.8.0
  - tqdm=4.66.5
  - nltk=3.9.1
  - pip
  - pip:
      - datasets==2.19.0
      - evaluate==0.4.2
      - sentence-transformers==2.6.1
      - transformers==4.41.2
      - accelerate==0.31.0
      - huggingface_hub==0.23.5
      - tokenizers==0.19.1
      - safetensors==0.4.3
